version: "3.1"
services:
    sasom_php:
      container_name: sasom_wordpress
      build:  .
      depends_on:
        - "sasom_db"
      environment:
        - WORDPRESS_DB_USER=wp
        - WORDPRESS_DB_PASSWORD=wordpress
        - WORDPRESS_DB_HOST=sasom_db
        - WORDPRESS_DB_NAME=wordpress
        - WORDPRESS_DOMAIN=localhost
        - WORDPRESS_ADMIN_USER=admin
        - WORDPRESS_ADMIN_PASSWORD=test
        - WORDPRESS_ADMIN_EMAIL=info@sasmo.de
      volumes:
        - type: bind
          source: ./data/wp-volume
          target: /www
          consistency: cached
        #- type: bind
        #  source: ./etc/certs
        #  target: /certs
        #  consistency: cached
      ports:
        - 80:80
      networks:
        - sasom-network

    sasom_db:
      container_name: sasom_db
      image: mariadb:10.6.0
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
        MYSQL_USER: wp
        MYSQL_PASSWORD: wordpress
        MYSQL_ROOT_PASSWORD: mysqlrootpw
        MYSQL_DATABASE: wordpress
      ports: [ '6033:3306' ]
      expose: [ '3306' ]
      volumes:
        - type: bind
          source: ./data/db-volume
          target: /var/lib/mysql
          consistency: cached
      networks:
        - sasom-network

    sasom_redis:
      container_name: sasom_redis
      image: "redis:alpine"
      command: redis-server --requirepass redispass
      ports:
        - "6379:6379"
      volumes:
        - type: bind
          source: ./data/redis-volume
          target: /var/lib/redis
          consistency: cached
        - type: bind
          source: ./etc/redis.conf
          target: /usr/local/etc/redis/redis.conf
          consistency: cached
      environment:
        - REDIS_REPLICATION_MODE=master
      networks:
        - sasom-network

    sasom_phpmyadmin:
      container_name: sasom_phpmyadmin
      image: phpmyadmin/phpmyadmin:4.7
      restart: always
      ports: [ '8081:80' ]
      links: [ 'sasom_db:sasom_db' ]
      environment:
        - PMA_HOST=sasom_db
        - PMA_USER=wp
        - PMA_PASSWORD=wordpress
        - PMA_ARBITRARY=1
      networks:
        - sasom-network

    sasom_mail:
      container_name: sasom_mail
      image: mailhog/mailhog
      ports:
        - "8025:8025"
        - "1025:1025"
      networks:
        - sasom-network

volumes:
  data:

networks:
  sasom-network:
    driver: bridge