version: "3.1"
services:
    wordpress:
      container_name: ${CONTAINER_PREFIX}-wordpress
      build:  .
      depends_on:
        - "db"
      environment:
        WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
        WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
        WORDPRESS_DB_HOST: db
        WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
        WORDPRESS_DOMAIN: ${WORDPRESS_DOMAIN}
        WORDPRESS_ADMIN_USER: ${WORDPRESS_ADMIN_USER}
        WORDPRESS_ADMIN_PASSWORD: ${WORDPRESS_ADMIN_PASSWORD}
        WORDPRESS_ADMIN_EMAIL: ${WORDPRESS_ADMIN_EMAIL}
        WORDPRESS_PORT: ${WORDPRESS_PORT}
        WORDPRESS_PORT_SSL: ${WORDPRESS_PORT_SSL}
      volumes:
        - type: bind
          source: ./data/wp-volume
          target: /www
          consistency: cached
        - type: bind
          source: ./etc/certs
          target: /certs
          consistency: cached
      ports:
        - ${WORDPRESS_PORT}:80
        - ${WORDPRESS_PORT_SSL}:443
      networks:
        - network

    db:
      container_name: ${CONTAINER_PREFIX}-db
      image: mariadb:10.6.0
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      ports:
        - ${MYSQL_PORT}:3306
      expose:
        - 3306
      volumes:
        - type: bind
          source: ./data/db-volume
          target: /var/lib/mysql
          consistency: delegated
      networks:
        - network

    redis:
      container_name: ${CONTAINER_PREFIX}-redis
      image: "redis:alpine"
      command: redis-server --requirepass redispass
      ports:
        - ${REDIS_PORT}:6379
      volumes:
        - type: bind
          source: ./etc/redis.conf
          target: /usr/local/etc/redis/redis.conf
          consistency: cached
      environment:
        REDIS_REPLICATION_MODE: ${REDIS_REPLICATION_MODE}
      networks:
        - network

    phpmyadmin:
      container_name: ${CONTAINER_PREFIX}-phpmyadmin
      image: phpmyadmin/phpmyadmin:4.7
      restart: always
      ports:
        - ${PMA_PORT}:80
      links:
        - db:db
      environment:
        PMA_HOST: db
        PMA_USER: ${WORDPRESS_DB_USER}
        PMA_PASSWORD: ${WORDPRESS_DB_PASSWORD}
        PMA_ARBITRARY: ${PMA_ARBITRARY}
      networks:
        - network

    mail:
      container_name: ${CONTAINER_PREFIX}-mail
      image: mailhog/mailhog
      ports:
        - ${MAILHOG_PORT_WEB_UI}:8025 # web ui
        - ${MAILHOG_PORT_SMTP}:1025 # smtp server
      networks:
        - network

volumes:
  data:

networks:
  network:
    driver: bridge